
variables:
  CMAKE_BUILD_ARGS: ""
  CMAKE_GENERATE_ARGS: ""
  URHO3D_CSHARP: ON
  URHO3D_SAMPLES: ON
  URHO3D_PACKAGING: ON
  TRACY_NO_INVARIANT_CHECK: 1

jobs:
  - job: Linux
    pool:
      vmImage: 'ubuntu-latest'

    variables:
      CMAKE_GENERATE_ARGS: -G Ninja

    strategy:
      matrix:
        shared-clang-opengl:
          BUILD_SHARED_LIBS: ON
          CMAKE_GENERATE_ARGS: -DTRACY_NO_PARALLEL_ALGORITHMS=ON
          CC: clang-8
          CXX: clang++-8
          EXTRA_PACKAGES: clang-8 mono-devel msbuild-libhostfxr msbuild-sdkresolver msbuild

    steps:
      - task: NuGetAuthenticate@0
      - bash: |
          # Mono
          sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
          echo "deb http://download.mono-project.com/repo/ubuntu stable-bionic main" | sudo tee /etc/apt/sources.list.d/mono-official-stable.list
          # Clang
          wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key|sudo apt-key add -
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test
          sudo apt-add-repository "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-8 main"
        displayName: 'Add Repositories'
      - bash: |
          sudo rm -f /usr/local/bin/cmake  ; bad azure-pipelines!
          wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | sudo apt-key add -
          sudo apt-add-repository 'deb https://apt.kitware.com/ubuntu/ bionic main'
          sudo apt-get update -y
          # Default compiler on this build worker image does not support c++17.
          sudo apt-get install -y --no-install-recommends cmake
        displayName: 'CMake'
      - bash: |
          sudo apt-get install -y --no-install-recommends libasound2-dev libxrandr-dev libgl1-mesa-dev libglu1-mesa-dev uuid-dev ninja-build $(EXTRA_PACKAGES)
          sudo update-alternatives --install /usr/bin/cc cc /usr/bin/$(CC) 100
          sudo update-alternatives --set cc /usr/bin/$(CC)
          sudo update-alternatives --install /usr/bin/c++ c++ /usr/bin/$(CXX) 100
          sudo update-alternatives --set c++ /usr/bin/$(CXX)
          mkdir "$(Build.SourcesDirectory)/SDK"
        displayName: 'Setup'
      
      - task: CMake@1
        displayName: Generate
        inputs:
          workingDirectory: cmake-build
          cmakeArgs: $(CMAKE_GENERATE_ARGS) -DCMAKE_INSTALL_PREFIX=$(Build.SourcesDirectory)/SDK -DCMAKE_BUILD_TYPE=RelWithDebInfo -DURHO3D_SAMPLES=ON -DURHO3D_CSHARP=$(URHO3D_CSHARP) -DURHO3D_PACKAGING=ON -DBUILD_SHARED_LIBS=$(BUILD_SHARED_LIBS) $(Build.SourcesDirectory)
